services:
  authservice_api:
      env_file:
          - .env
      build:
          context: .
          dockerfile: ./src/AuthService/AuthService.Api/Dockerfile
      ports:
        - "7210:8080"
      container_name: authservice_container
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      depends_on:
        postgre_db:
          condition: service_started
          
  userservice_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./src/UserService/UserService.Api/Dockerfile   
    ports:
      - "7143:8080"
    container_name: userservice_container  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
    depends_on:
      mongo_db:
        condition: service_started
  
  mongo_db:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongo_db
    
  postgre_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgresql_db_container

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    container_name: pg_admin_container
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgre_db
      - postgre_db

volumes:
  mongo_data:
  db_data:
  pgadmin-data:

      
    
      
