services:
  maildev:
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1:1080 || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
  
  authservice_api:
    build:
      context: .
      dockerfile: ./src/AuthService/AuthService.Api/Dockerfile
    ports:
      - "7210:8080"
    container_name: authservice_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Smtp__Host=maildev
    depends_on:
      maildev:
        condition: service_healthy
      postgre_db:
        condition: service_started
         
  postgre_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: FriendsApp
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgresql_db_container
    

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    container_name: pg_admin_container
    ports:
      - "5050:80"
    volumes:
        - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgre_db
          
volumes:
  db_data:
  pgadmin-data:
      
    
      
