@ApiGateway_HostAddress = http://localhost:5100

GET {{ApiGateway_HostAddress}}/friendship/my-friends/928803a2-11b2-45be-be29-c666c52eef19
Accept: application/json

###
GET https://192.168.0.186/api/account/confirm-email?userId=67dfd520-3b46-4ff4-b995-1470ba6d218f&token=Q2ZESjhCWmMwNzJPN0g1S2hpVTFKSm9GWDZjL29GL2QyQ3hnRFdoZG0wMW5lWnpJcDV6Q25LT0RLd0tUUE5JcjhrVXlsTTJ6TXU4aGRTNlhqU0d4NjEzL1JYdmhxRHhnQncyVDZoNE5zVGc4TjdrRU95MkxzT2xCaHN6TGJlNXovVHNUSEd4MUtnSmZTaEpPU2JYS09mQ3RGUHh6RjNOU0sxMUd6NGI0Tm4vSEhQZzJzNVhpR25SQ05JWXdOdWw1bkQrdUF2UXpVSEtUSmZMWThoUldMQUZEOTArdVFFbktKS3Q0WC9SdlZQZTk3ZzZCcU5FR3pjWmFzWk1xK2xFTDRzMTRJQT09